model:
  RandomForestRegressor:
    n_estimators: 200
    max_depth: 10
    min_samples_split: 15

hyperparameters:
  RandomForestRegressor:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10, 15]
    min_samples_split: [5, 10, 15]
